version: "3.9"

services:
  postgres:
    image: postgres:15
    hostname: store-postgres
    container_name: store-postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: store
    networks:
      - store-network
    ports:
      - "2345:5432"

  nginx:
    hostname: store-nginx
    container_name: store-nginx
    build: ./docker/nginx
    volumes:
      - .:/var/www/app
    depends_on:
      - postgres
      - fpm
    networks:
      - store-network
    ports:
      - "8080:80"

      
  fpm:
    build: ./docker
    hostname: store-fpm
    container_name: store-fpm
    volumes:
      - ".:/var/www/app"
    networks:
      - store-network

networks:
  store-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.0.0.0/24"
        - subnet: "2001:3984:3989::/64"